=== stbenigma/Information-model-standard/Model/im-standard-schema/MetaModel/MME-schema.json
{
  "$id": "MME-schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Meta-Model-Environment.\n  Collection of all data about your datauniverse (= meta data)",
  "contact": {
    "email": "stefan@stefanberner.ch"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "servers": [
    {
      "url": "https:"
    }
  ],
  "version": "0.9",
  "externalDocs": [
  ],
  "type": "object",
  "properties": {
    "MetaModelInfo": {
      "description": "",
      "allOf": [
        {
          "$ref": "../GeneralDefinitions/GeneralStructures-schema.json#/$defs/BaseModelInfo"
        }
      ]
    },
    "Models": {
      "description": "List of all models building up the meta model",
      "type": "array",
      "additionalProperties": {
        "oneOf": [
          {
            "$ref": "../InformationModel/InformationModel-schema.json"
          },
          {
            "$ref": "../DataModel/DataModel-schema.json"
          }
        ]
      },
      "uniqueItems": true
    },
    "Derivations": {
      "description": "List derivations, connecting elements semantically cross-models",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/$defs/Derivation"
      }
    },
    "Mappings": {
      "description": "List Mappings, linking LOV-values of different LOV's together. Can connect LOV-values cross models",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/$defs/Mapping"
      }
    },
    "Transformations": {
      "description": "List transformations from any dataelements to any other dataelements.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/$defs/Transformation"
      }
    },
    "Sources": {
      "description": "List of external sources providing information restricting, explaining, or enhancing the my definitions.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/$defs/Source"
      }
    },
    "Organisations": {
        "description": "Corporation (association, federation, cooperative, standards organisation, consortium) that are mostly non-profit-oriented..",
        "type": "object",
        "properties": {
          "elementId": {
        "description": "unique ID of the organisation for reference purposes",
        "$ref": "MetaModel-schema.json#/$defs/OrganisationId"
    },
          "name": {
            "description": "Name of the source. unique within the MME",
            "$ref": "../GeneralDefinitions/GeneralTypes-schema.json#/$defs/Name",
            "examples": ["ISO-Standard 3166", "Schweizer Zoll Tarifseite"]
          },
        "description": {
          "$ref": "../GeneralDefinitions/GeneralTypes-schema.json#/$defs/SomeText"
        },
          "email": {
            "description": "main email address of the organisation",
            "$ref": "../GeneralDefinitions/GeneralTypes-schema.json#/$defs/Email",
            "examples": ["ISO", "Schweizer Zoll"]
          },
          "url": {
            "description": "worldwide uniqe reference where to find the documentation ",
            "$ref": "../GeneralDefinitions/GeneralTypes-schema.json#/$defs/Url",
            "examples": ["https://www.iso.org/iso-3166-country-codes.html", "https://xtares.admin.ch/tares/login/loginFormFiller.do?l=de"]
          },
          "additionalProps": {
            "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
            "$ref": "../GeneralDefinitions/GeneralStructures-schema.json#/$defs/AdditionalProperties"
          }
        },
        "required": [
          "elementId","name"
        ],
        "additionalProperties": false
      },
    "additionalProps": {
      "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
      "$ref": "../GeneralDefinitions/GeneralStructures-schema.json#/$defs/AdditionalProperties"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "required": [
    "MetaModelInfo"
  ]
}

=== stbenigma/Information-model-standard/Model/im-standard-schema/model-validation/testmodels/MetaModel/MME/valid/minimal+1.json
{
  "MetaModelInfo": {
    "modelName": "Test model",
    "targetEnvironment": "test infomodel",
    "modelVersion": "0.1",
    "modelType": "Meta model"
  },
  "Models": [{
    "Informationsmodell": {
      "ModelInfo": {
        "modelName": "Informationsmodell",
        "targetEnvironment": "information model standard",
        "modelVersion": "0.1",
        "modelType": "Information model"
      }
    }
  }],
  "Derivations": [],
  "Mappings": [],
  "Transformations": []
}
