=== stbenigma/Information-model-standard/im-standard-json/InformationModel-schema.json
{
  "$id": "InformationModel-schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Information Model.\n  Based on the relational model and described in the book Information Modelling.",
  "contact": {
    "email": "stefan@stefanberner.ch"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "servers": [
    {
      "url": "https:"
    }
  ],
  "version": "0.9",
  "externalDocs": [
    {
      "title": "Information modelling - A method for improving understanding and accuracy in your collaboration",
      "description": "Original book written by Stefan Berner, describing the information model",
      "url": "https://vdf.ch/information-modelling.html"
    }
  ],
  "type": "object",
  "components": {
    "schemas": {},
    "$defs": {}
  },
  "properties": {
    "ModelInfo": {
      "description": "",
      "allOf": [
        {
          "$ref": "GeneralStructures-schema.json#/components/schemas/BaseModelInfo"
        },
        {
          "type": "object",
          "description": "Attributes specific for an information model",
          "properties": {
            "modeltype": {
              "const": "Information model"
            },
            "mainlanguage": {
              "description": "Main (and possibly only) language of the models textelements. Serves as default language in multilingual strings, whenever for any of the languages a translation is missing.",
              "$ref": "GeneralTypes-schema.json#/components/$defs/LanguageIso2"
            },
            "languages": {
              "description": "List of languages, model textelements can be translated to. Excluding mainLanguage. The mainlanguage must be present in every multilingual string.",
              "type": "array",
              "items": {
                "$ref": "GeneralTypes-schema.json#/components/$defs/LanguageIso2"
              },
              "uniqueItems": true
            }
          }
        }
      ]
    },
    "Entities": {
      "description": "List of entities making up this model",
      "type": "array",
      "items": {
        "$ref": "Entity-schema.json"
      },
      "uniqueItems": true
    },
    "Attributes": {
      "description": "List of attributes of entities and groupdomains. The names of all attributes within one entity (or within one domain) must be unique",
      "type": "array",
      "items": {
        "$ref": "Attribute-schema.json"
      }
    },
    "Domains": {
      "description": "List of domain used in this model",
      "type": "array",
      "items": {
        "$ref": "Domain-schema.json"
      }
    },
    "Relations": {
      "description": "List of relations in this model",
      "type": "array",
      "items": {
        "$ref": "Relation-schema.json"
      }
    },
    "BusinessRules": {
      "description": "List of business rules.",
      "type": "array",
      "items": {
        "$ref": "BusinessRule-schema.json"
      }
    },
    "Categories": {
      "description": "List of categories, used to group elements in this model.",
      "type": "array",
      "items": {
        "$ref": "Category-schema.json"
      }
    },
    "Derivations":{
      "description": "List derivations, an element of this model is a target in.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Derivation"
      }
    },
    "Mappings":{
      "description": "List Mappings, linking LOV-values of different LOV's together. The source or target LOV-domain must me in this model.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Mapping"
      }
    },
    "Transformations":{
      "description": "List transformations from some dataelements to other dataelements. At least one source or target dataelement  must me in this model.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Transformation"
      }
    },
    "Diagrams":{
      "description": "List of diagrams, combining model elements into a view of chosen elements",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Diagram"
      }
    },
    "additionalProps": {
      "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
      "$ref": "GeneralStructures-schema.json#/components/schemas/AdditionalProperties"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "required": [
    "ModelInfo"
  ]
}

=== stbenigma/Information-model-standard/im-standard-json/testmodels/InformationModel/valid/derivation.json
{
  "ModelInfo": {
    "modelname": "Beispielmodell Astronomie",
    "modeltype": "Information model",
    "mainlanguage": "de",
    "modelversion": "0.9",
    "languages": [
      "en"
    ],
    "targetenvironment": "Informatiosmodell Standard",
    "origintool": "dataspot"
  },
  "Categories": [
    {
      "elementid": "CATG0",
      "name": "myname",
      "categorytype": "ENTITY",
      "categoryid": "CATG1"
    }
  ],
  "Domains": [
    {
      "elementid": "DOMA26",
      "name": {
        "de": "Leuchtklasse",
        "en": "Luminosity class"
      },
      "description": {
        "de": "Leuchtkraftklassen (Helligkeitstypen) \nI\t\u00dcberriesen\tBetelgeuse (M1I)\nII\tHelle Riesen\t\nIII\tRiesen\tAldebaran (K5III)\nIV\tUnterriesen\t\nV\tHauptreihe (normale Sterne)\tSonne (G2V)\nVI\tUnterzwerge\t\nD\tWei\u00dfe Zwerge\tSirius B",
        "en": "Luminosity classes (brightness types)\nI Supergiant Betelgeuse (M1I)\nII Bright giants\nIII Giants Aldebaran (K5III)\nIV Subgiants\nV Main sequence (normal stars) Sun (G2V)\nVI Subdwarfs\nD White dwarfs Sirius B"
      },
      "categoryid": "CATG5",
      "domaintype": "LOVDomain",
      "values": [
        {
          "value": "VI",
          "displayvalue": {
            "de": "Unterzwerge",
            "en": "Subdwarfs"
          },
          "description": {
            "de": "auch sd, Betelgeuse (M1I)"
          }
        },
        {
          "value": "III",
          "displayvalue": {
            "de": "Riesen",
            "en": "Giants"
          },
          "description": {
            "de": "Aldebaran (K5III)"
          }
        },
        {
          "value": "I",
          "displayvalue": {
            "de": "\u00dcberriese",
            "en": "Supergiant"
          },
          "description": {
            "de": "Unterteilung der \u00dcberriesen nach abnehmender Leuchtkraft Ia-0, Ia, Iab, Ib"
          }
        },
        {
          "value": "V",
          "displayvalue": {
            "de": "Hauptreihe",
            "en": "Main sequence"
          },
          "description": {
            "de": "normale Stern, Sonne (G2V)"
          }
        },
        {
          "value": "0",
          "displayvalue": {
            "de": "Hyperriese",
            "en": "Supergiant"
          },
          "description": {
            "de": "Deneb, S Doradus"
          }
        },
        {
          "value": "VII",
          "displayvalue": {
            "de": "Wei\u00dfe Zwerge",
            "en": "White dwarf"
          },
          "description": {
            "de": "Auch D,  Sirius B"
          }
        },
        {
          "value": "IV",
          "displayvalue": {
            "de": "Unterriesen",
            "en": "Subgiants"
          }
        },
        {
          "value": "II",
          "displayvalue": {
            "de": "Helle Riesen",
            "en": "Bright Giants"
          }
        }
      ]
    }
  ],
  "Entities": [
    {
      "elementid": "ENTI1",
      "name": {
        "de": "Mond",
        "en": "Planets Moon"
      },
      "shortdescr": {
        "de": "Fester Himmelsk\u00f6rper der um einen Planeten kreist",
        "en": "Fixed celestial body orbiting a planet"
      },
      "examples": [
        "(Erd-)Mond",
        "Phobos",
        "Deimos",
        "Io",
        "Europa",
        "Ganymed",
        "Triton",
        "Charon"
      ],
      "keys": [
        [
          "RELA2",
          "ATTR27"
        ]
      ]
    }
  ],
  "Attributes": [
    {
      "elementid": "ATTR0",
      "name": "Attr1",
      "parentid": "ENTI0",
      "displayseq": 2,
      "domainid": "DOMA001",
      "descriptive": true,
      "historicised": false,
      "translated": true,
      "examples": [
        "Farbe",
        "Koordinate"
      ],
      "description": {
        "en": "Purpose, usage, meaning of an attribute value hold by this attribute."
      },
      "shortdescr": "Short text to be displayed as help to understand the purpose of this attribute in user interfaces.",
      "mandatory": true,
      "repeated": true,
      "encrypted": false,
      "additionalProps": {
        "$comment": "Entityattribute, see parent"
      }
    }
  ],
  "Relations": [
    {
      "elementid": "RELA8",
      "relationtype": "SUBTYPE",
      "fwd": {
        "entityid": "ENTI7",
        "assoctext": {
          "de": "ist",
          "en": "is"
        },
        "cardinality": "1",
        "mandatory": true
      },
      "bwd": {
        "entityid": "ENTI1",
        "assoctext": {
          "de": "ist",
          "en": "is"
        },
        "cardinality": "1",
        "mandatory": true,
        "arcnumber": 0
      }
    }
  ],
  "BusinessRules": [
    {
      "elementid": "BURU3",
      "restrictedelements": [
        "ENTI5"
      ],
      "description": "Ein Asteriod umkreist immer genau einen Stern oder einen Asteroiden (aber nicht sich selbst)"
    }
  ],
  "Derivations": [
    {
      "derivationtype": "defines",
      "sourceelement": "RELA01",
      "targetelement": "DOMA1287"
    },
    {
      "derivationtype": "defines",
      "sourceelement": "AnderesModell:ENTI01",
      "targetelement": "DOMA1287"
    },
    {
      "targetelement": "DOMA1287",
      "derivationtype": "restrict",
      "sourceelement": "/Systemmodell/Datenbanken/ZentralDB",
      "additionalProps": {
        "sourcereference": "/modelx/elementy"
      }
    }
  ],
  "Mappings": [
    {
      "sourcedomain": "DOMA01",
      "targetdomain": "DOMA02",
      "valuemappings": [
        [
          "CH",
          "SCHWEIZ"
        ],
        [
          "FR",
          "France"
        ]
      ],
      "additionalProps": {
        "$comment": "Entityattribute, see parent"
      }
    },
    {
      "sourcedomain": "DOMA01",
      "targetdomain": "DOMA02",
      "valuemappings": [
        [
          1,
          true
        ],
        [
          "FR",
          9999
        ]
      ],
      "additionalProps": {
        "$comment": "Entityattribute, see parent"
      }
    }
  ],
  "Transformations": [
    {
      "is1to1": false,
      "fwd": {
        "rule": "1+1",
        "condition": "Bedingung"
      },
      "bwd": {
        "rule": "",
        "condition": "",
        "additionalProps": {
          "$comment": "Entityattribute, see parent"
        }
      },
      "sourceelements": [
        "ATTR00",
        "Anderes Modell:DOMA99"
      ],
      "targetelements": [
        "RELA199",
        "/Systemmodel/Group-I/localdatabase"
      ],
      "additionalProps": {
        "$comment": "Entityattribute, see parent"
      }
    }
  ],
  "additionalProps": {
    "Who": "me"
  }
}
