=== stbenigma/Information-model-standard/im-standard-json/MME-schema.json
{
  "$id": "MME-schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Meta-Model-Environment.\n  Collection of all data about your datauniverse (= meta data)",
  "contact": {
    "email": "stefan@stefanberner.ch"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "servers": [
    {
      "url": "https:"
    }
  ],
  "version": "0.9",
  "externalDocs": [
  ],
  "type": "object",
  "components": {
    "schemas": {},
    "$defs": {}
  },
  "properties": {
    "MetaModelInfo": {
      "description": "",
      "allOf": [
        {
          "$ref": "GeneralStructures-schema.json#/components/schemas/BaseModelInfo"
        }
      ]
    },
    "Models": {
      "description": "List of all models building up the meta model",
      "type": "array",
      "additionalProperties": {
        "oneOf": [
          {
            "$ref": "InformationModel-schema.json"
          },
          {
            "$ref": "DataModel-schema.json"
          }
        ]
      },
      "uniqueItems": true
    },
    "Derivations": {
      "description": "List derivations, connecting elements semantically cross-models",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Derivation"
      }
    },
    "Mappings": {
      "description": "List Mappings, linking LOV-values of different LOV's together. Can connect LOV-values cross models",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Mapping"
      }
    },
    "Transformations": {
      "description": "List transformations from any dataelements to any other dataelements.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Transformation"
      }
    },
    "Sources": {
      "description": "List of external sources providing information restricting, explaining, or enhancing the my definitions.",
      "type": "array",
      "items": {
        "$ref": "MetaModel-schema.json#/components/schemas/Source"
      }
    },
    "Organisations": {
        "description": "Corporation (association, federation, cooperative, standards organisation, consortium) that are mostly non-profit-oriented..",
        "type": "object",
        "properties": {
          "elementid": {
        "description": "unique ID of the organisation for reference purposes",
        "$ref": "MetaModel-schema.json#/components/$defs/OrganisationId"
    },
          "name": {
            "description": "Name of the source. unique within the MME",
            "$ref": "GeneralTypes-schema.json#/components/$defs/Name",
            "examples": ["ISO-Standard 3166", "Schweizer Zoll Tarifseite"]
          },
        "description": {
          "$ref": "GeneralTypes-schema.json#/components/$defs/SomeText"
        },
          "email": {
            "description": "main email address of the organisation",
            "$ref": "GeneralTypes-schema.json#/components/$defs/Email",
            "examples": ["ISO", "Schweizer Zoll"]
          },
          "url": {
            "description": "worldwide uniqe reference where to find the documentation ",
            "$ref": "GeneralTypes-schema.json#/components/$defs/Url",
            "examples": ["https://www.iso.org/iso-3166-country-codes.html", "https://xtares.admin.ch/tares/login/loginFormFiller.do?l=de"]
          },
          "additionalProps": {
            "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
            "$ref": "GeneralStructures-schema.json#/components/schemas/AdditionalProperties"
          }
        },
        "required": [
          "elementid","name"
        ],
        "additionalProperties": false
      },
    "additionalProps": {
      "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
      "$ref": "GeneralStructures-schema.json#/components/schemas/AdditionalProperties"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "required": [
    "MetaModelInfo"
  ]
}

=== stbenigma/Information-model-standard/im-standard-json/testmodels/MME/valid/minimal+1.json
{
  "MetaModelInfo": {
    "modelname": "Test model",
    "targetenvironment": "test infomodel",
    "modelversion": "0.1",
    "modeltype": "Meta model"
  },
  "Models": [{
    "Informationsmodell": {
      "ModelInfo": {
        "modelname": "Informationsmodell",
        "targetenvironment": "information model standard",
        "modelversion": "0.1",
        "modeltype": "Information model"
      }
    }
  }],
  "Derivations": [],
  "Mappings": [],
  "Transformations": []
}
