=== stbenigma/Information-model-standard/Model/im-standard-schema/InformationModel/InformationModel-schema.json
{
  "$id": "InformationModel-schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Information model.\n  Based on the relational model and described in the book Information Modelling.",
  "contact": {
    "email": "stefan@stefanberner.ch"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "servers": [
    {
      "url": "https:"
    }
  ],
  "version": "0.9",
  "externalDocs": [
    {
      "title": "Information modelling - A method for improving understanding and accuracy in your collaboration",
      "description": "Original book written by Stefan Berner, describing the information model",
      "url": "https://vdf.ch/information-modelling.html"
    }
  ],
  "type": "object",
  "properties": {
    "ModelInfo": {
      "description": "",
      "allOf": [
        {
          "$ref": "../GeneralDefinitions/GeneralStructures-schema.json#/$defs/BaseModelInfo"
        },
        {
          "type": "object",
          "description": "Attributes specific for an information model",
          "properties": {
            "modelType": {
              "const": "Information model"
            },
            "mainLanguage": {
              "description": "Main (and possibly only) language of the models textelements. Serves as default language in multilingual strings, whenever for any of the languages a translation is missing.",
              "$ref": "../GeneralDefinitions/GeneralTypes-schema.json#/$defs/LanguageIso2"
            },
            "languages": {
              "description": "List of languages, model textelements can be translated to. Excluding mainLanguage. The mainlanguage must be present in every multilingual string.",
              "type": "array",
              "items": {
                "$ref": "../GeneralDefinitions/GeneralTypes-schema.json#/$defs/LanguageIso2"
              },
              "uniqueItems": true
            },
            "additionalProps": {
      "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
      "$ref": "../GeneralDefinitions/GeneralStructures-schema.json#/$defs/AdditionalProperties"
    }
          }
        }
      ]
    },
    "Entities": {
      "description": "List of entities making up this model",
      "type": "array",
      "items": {
        "$ref": "../InformationModel/Entity-schema.json"
      },
      "uniqueItems": true
    },
    "Attributes": {
      "description": "List of attributes of entities and groupdomains. The names of all attributes within one entity (or within one domain) must be unique",
      "type": "array",
      "items": {
        "$ref": "../InformationModel/Attribute-schema.json"
      }
    },
    "Domains": {
      "description": "List of domain used in this model",
      "type": "array",
      "items": {
        "$ref": "../GeneralDefinitions/Domain-schema.json"
      }
    },
    "Relations": {
      "description": "List of relations in this model",
      "type": "array",
      "items": {
        "$ref": "../InformationModel/Relation-schema.json"
      }
    },
    "BusinessRules": {
      "description": "List of business rules.",
      "type": "array",
      "items": {
        "$ref": "../GeneralDefinitions/BusinessRule-schema.json"
      }
    },
    "Categories": {
      "description": "List of categories, used to group elements in this model.",
      "type": "array",
      "items": {
        "$ref": "../GeneralDefinitions/Category-schema.json"
      }
    },
    "Derivations":{
      "description": "List derivations, an element of this model is a target in.",
      "type": "array",
      "items": {
        "$ref": "../MetaModel/MetaModel-schema.json#/$defs/Derivation"
      }
    },
    "Mappings":{
      "description": "List Mappings, linking LOV-values of different LOV's together. The source or target LOV-domain must me in this model.",
      "type": "array",
      "items": {
        "$ref": "../MetaModel/MetaModel-schema.json#/$defs/Mapping"
      }
    },
    "Transformations":{
      "description": "List transformations from some dataelements to other dataelements. At least one source or target dataelement  must me in this model.",
      "type": "array",
      "items": {
        "$ref": "../MetaModel/MetaModel-schema.json#/$defs/Transformation"
      }
    },
    "Diagrams":{
      "description": "List of diagrams, combining model elements into a view of chosen elements",
      "type": "array",
      "items": {
        "$ref": "../MetaModel/MetaModel-schema.json#/$defs/Diagram"
      }
    },
    "additionalProps": {
      "description": "additional properties (aka user defined properties udp) are  any properties of an this element  added by the current modeller. They serve as an extension to the predfefined element properties.",
      "$ref": "../GeneralDefinitions/GeneralStructures-schema.json#/$defs/AdditionalProperties"
    }
  },
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "required": [
    "ModelInfo"
  ]
}

=== stbenigma/Information-model-standard/Example models/MinimalModels/minimalistic_IM.json
{
  "ModelInfo": {
    "modelName": "Information model",
    "targetEnvironment": "information model standard",
    "modelVersion": "0.1",
    "modelType": "Information model",
    "description": "show 2 entities with 1 relationship and some attributes, no details, just names"
  },
  "Entities": [
    {
      "elementId": "ENTI1",
      "name": "Something",
      "examples": [
        "This",
        "That"
      ]
    },
    {
      "elementId": "ENTI2",
      "name": "Another Thing"
    }
  ],
  "Relations": [
    {
      "elementId": "RELA1",
      "relationType": "M:1",
      "fwd": {
        "entityId": "ENTI1",
        "assocText": "linked to",
        "cardinality": "1",
        "mandatory": true
      },
      "bwd": {
        "entityId": "ENTI2",
        "cardinality": "M",
        "mandatory": false
      }
    }
  ],
  "Attributes": [
    {
      "elementId": "ATTR1",
      "name": "Name",
      "mandatory": false,
      "parentId": "ENTI1"
    },
    {
      "elementId": "ATTR2",
      "name": "Status",
      "mandatory": true,
      "parentId": "ENTI2",
      "examples":["on", "off"]
    }
  ]
}

=== stbenigma/Information-model-standard/Model/im-standard-schema/model-validation/testmodels/InformationModel/InformationModel/valid/maximum.json
{
  "ModelInfo": {
    "modelName": "Beispielmodell Astronomie",
    "modelType": "Information model",
    "mainLanguage": "de",
    "modelVersion": "0.9",
    "languages": [
      "en"
    ],
    "targetEnvironment": "Informatiosmodell Standard",
    "originTool": "dataspot"
  },
  "Categories": [
    {
      "elementId": "CATG0",
      "name": "myname",
      "categoryType": "ENTITY",
      "categoryId": "CATG1"
    }
  ],
  "Domains": [
    {
      "elementId": "DOMA26",
      "name": {
        "de": "Leuchtklasse",
        "en": "Luminosity class"
      },
      "description": {
        "de": "Leuchtkraftklassen (Helligkeitstypen) \nI\t\u00dcberriesen\tBetelgeuse (M1I)\nII\tHelle Riesen\t\nIII\tRiesen\tAldebaran (K5III)\nIV\tUnterriesen\t\nV\tHauptreihe (normale Sterne)\tSonne (G2V)\nVI\tUnterzwerge\t\nD\tWei\u00dfe Zwerge\tSirius B",
        "en": "Luminosity classes (brightness types)\nI Supergiant Betelgeuse (M1I)\nII Bright giants\nIII Giants Aldebaran (K5III)\nIV Subgiants\nV Main sequence (normal stars) Sun (G2V)\nVI Subdwarfs\nD White dwarfs Sirius B"
      },
      "categoryId": "CATG5",
      "domainType": "LOVDomain",
      "values": [
        {
          "value": "VI",
          "displayValue": {
            "de": "Unterzwerge",
            "en": "Subdwarfs"
          },
          "description": {
            "de": "auch sd, Betelgeuse (M1I)"
          }
        },
        {
          "value": "III",
          "displayValue": {
            "de": "Riesen",
            "en": "Giants"
          },
          "description": {
            "de": "Aldebaran (K5III)"
          }
        },
        {
          "value": "I",
          "displayValue": {
            "de": "\u00dcberriese",
            "en": "Supergiant"
          },
          "description": {
            "de": "Unterteilung der \u00dcberriesen nach abnehmender Leuchtkraft Ia-0, Ia, Iab, Ib"
          }
        },
        {
          "value": "V",
          "displayValue": {
            "de": "Hauptreihe",
            "en": "Main sequence"
          },
          "description": {
            "de": "normale Stern, Sonne (G2V)"
          }
        },
        {
          "value": "0",
          "displayValue": {
            "de": "Hyperriese",
            "en": "Supergiant"
          },
          "description": {
            "de": "Deneb, S Doradus"
          }
        },
        {
          "value": "VII",
          "displayValue": {
            "de": "Wei\u00dfe Zwerge",
            "en": "White dwarf"
          },
          "description": {
            "de": "Auch D,  Sirius B"
          }
        },
        {
          "value": "IV",
          "displayValue": {
            "de": "Unterriesen",
            "en": "Subgiants"
          }
        },
        {
          "value": "II",
          "displayValue": {
            "de": "Helle Riesen",
            "en": "Bright Giants"
          }
        }
      ]
    }
  ],
  "Entities": [
    {
      "elementId": "ENTI1",
      "name": {
        "de": "Mond",
        "en": "Planets Moon"
      },
      "shortDescr": {
        "de": "Fester Himmelsk\u00f6rper der um einen Planeten kreist",
        "en": "Fixed celestial body orbiting a planet"
      },
      "examples": [
        "(Erd-)Mond",
        "Phobos",
        "Deimos",
        "Io",
        "Europa",
        "Ganymed",
        "Triton",
        "Charon"
      ],
      "keys": [
        {"name":"1","elements":[
          "RELA2",
          "ATTR27"
        ]}
      ]
    }
  ],
  "Attributes": [
    {
      "elementId": "ATTR0",
      "name": "Attr1",
      "parentId": "ENTI0",
      "displaySeq": 2,
      "domainId": "DOMA001",
      "descriptive": true,
      "historicised": false,
      "translated": true,
      "examples": [
        "Farbe",
        "Koordinate"
      ],
      "description": {
        "en": "Purpose, usage, meaning of an attribute value hold by this attribute."
      },
      "shortDescr": "Short text to be displayed as help to understand the purpose of this attribute in user interfaces.",
      "mandatory": true,
      "repeated": true,
      "encrypted": false,
      "additionalProps":
        {
          "$comment": "Entityattribute, see parent"
        }
    }
  ],
  "Relations": [
    {
      "elementId": "RELA8",
      "relationType": "SUBTYPE",
      "fwd": {
        "entityId": "ENTI7",
        "assocText": {
          "de": "ist",
          "en": "is"
        },
        "cardinality": "1",
        "mandatory": true
      },
      "bwd": {
        "entityId": "ENTI1",
        "assocText": {
          "de": "ist",
          "en": "is"
        },
        "cardinality": "1",
        "mandatory": true,
        "arcNumber": 0
      }
    }
  ],
  "BusinessRules": [
    {
      "elementId": "BURU3",
      "restrictedElements": [
        "ENTI5"
      ],
      "description": "Ein Asteriod umkreist immer genau einen Stern oder einen Asteroiden (aber nicht sich selbst)"
    }
  ],
  "additionalProps":
    {
      "Who": "me"
    }
}
